### ISSUE TITLE
How to compare images with robot framework in window based environement ?

### ISSUE THREAD

**Issue by dipakbachhav** [ThomasJaspers/robot-framework-image-comparison#1]
I am using imagemagick to compare two screenshots in windows environment.https://blog.codecentric.de/en/2017/09/robot-framework-compare-images-screenshots/

```

*** Settings ***
Library   String
Library   OperatingSystem

*** Variables ***
${IMAGE_COMPARATOR_COMMAND}   C:\\"Program Files"\\ImageMagick-7.0.7-Q16\\convert.exe


*** Test Cases ***
Image Comparison Ok
  Compare Images    C:/Users/user/imagecompare/Test/src/reference-screenshots/reference-1.png    C:/Users/user/imagecompare/Test/src/test-screenshots/test-1.png   0.1


Image Comparison NOk
  Compare Images    C:/Users/user/imagecompare/Test/src/reference-screenshots/reference-1.png    C:/Users/user/imagecompare/Test/src/test-screenshots/test-1.png   0.1

*** Keywords ***
Compare Images
   [Arguments]      ${Reference_Image_Path}    ${Test_Image_Path}    ${Allowed_Threshold}
   ${TEMP}=         Replace String     ${IMAGE_COMPARATOR_COMMAND}    __REFERENCE__     ${Reference_Image_Path}
   ${COMMAND}=      Replace String     ${TEMP}    __TEST__     ${Test_Image_Path}
   Log              Executing: ${COMMAND}
   ${RC}            ${OUTPUT}=     Run And Return Rc And Output     ${COMMAND}
   Log              Return Code: ${RC}
   Log              Return Output: ${OUTPUT}
   ${RESULT}        Evaluate    ${OUTPUT} < ${Allowed_Threshold}
   Should be True   ${RESULT}



```
But facing issue with above code.

**Comment by ThomasJaspers** [comment]
What kind of issue :-)?

**Comment by dipakbachhav** [comment]
Below are the issue:  i have tried to compare same image but failed. Also I am using windows environment. Please help me out as i am seriously struggling with image comparison from past 2 weeks.  

Evaluates the given expression in Python and returns the results.
Start / End / Elapsed:	20171017 15:02:12.842 / 20171017 15:02:12.843 / 00:00:00.001
15:02:12.843	FAIL	Evaluating expression 'Version: ImageMagick 7.0.7-8 Q16 x64 2017-10-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo flif freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps raw rsvg tiff webp xml zlib
Usage: compare.exe [options ...] image reconstruct difference

Image Settings:
  -alpha option        on, activate, off, deactivate, set, opaque, copy
                       transparent, extract, background, or shape
  -authenticate password
                       decipher image with this password
  -background color    background color
  -colorspace type     alternate image colorspace
  -compose operator    set image composite operator
  -compress type       type of pixel compression when writing the image
  -decipher filename   convert cipher pixels to plain pixels
  -define format:option
                       define one or more image format options
  -density geometry    horizontal and vertical density of the image
  -depth value         image depth
  -dissimilarity-threshold value
                       maximum distortion for (sub)image match
  -encipher filename   convert plain pixels to cipher pixels
  -extract geometry    extract area from image
  -format "string"     output formatted image characteristics
  -fuzz distance       colors within this distance are considered equal
  -gravity type        horizontal and vertical text placement
  -highlight-color color
                       empasize pixel differences with this color
  -identify            identify the format and characteristics of the image
  -interlace type      type of image interlacing scheme
  -limit type value    pixel cache resource limit
  -lowlight-color color
                       de-emphasize pixel differences with this color
  -metric type         measure differences between images with this metric
  -monitor             monitor progress
  -negate              replace every pixel with its complementary color 
  -profile filename    add, delete, or apply an image profile
  -quality value       JPEG/MIFF/PNG compression level
  -quiet               suppress all warning messages
  -quantize colorspace reduce colors in this colorspace
  -read-mask filename  associate a read mask with the image
  -regard-warnings     pay attention to warning messages
  -respect-parentheses settings remain in effect until parenthesis boundary
  -sampling-factor geometry
                       horizontal and vertical sampling factor
  -seed value          seed a new sequence of pseudo-random numbers
  -set attribute value set an image attribute
  -quality value       JPEG/MIFF/PNG compression level
  -repage geometry     size and location of an image canvas
  -similarity-threshold value
                       minimum distortion for (sub)image match
  -size geometry       width and height of image
  -subimage-search     search for subimage
  -synchronize         synchronize image to storage device
  -taint               declare the image as modified
  -transparent-color color
                       transparent color
  -type type           image type
  -verbose             print detailed information about the image
  -version             print version information
  -virtual-pixel method
                       virtual pixel access method
  -write-mask filename  associate a write mask with the image

Image Operators:
  -brightness-contrast geometry
                       improve brightness / contrast of the image
  -distort method args
                       distort images according to given method and args
  -level value         adjust the level of image contrast
  -resize geometry     resize the image
  -rotate degrees      apply Paeth rotation to the image
  -sigmoidal-contrast geometry
                       increase the contrast without saturating highlights or
  -trim                trim image edges
  -write filename      write images to this file

Image Channel Operators:
  -separate            separate an image channel into a grayscale image

Image Sequence Operators:
  -crop geometry       cut out a rectangular region of the image

Image Stack Operators:
  -delete indexes      delete the image from the image sequence

Miscellaneous Options:
  -channel mask        set the image channel mask
  -debug events        display copious debugging information
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information

By default, the image format of 'file' is determined by its magic
number.  To specify a particular image format, precede the filename
with an image format name and a colon (i.e. ps:image) or specify the
image type as the filename suffix (i.e. image.ps).  Specify 'file' as
'-' for standard input or output. < 0.1' failed: SyntaxError: invalid syntax (<string>, line 1)

**Comment by dipakbachhav** [comment]
Command: C:\Python27\python.exe -m robot.run --listener C:\Users\DIPAK~1.BAC\AppData\Local\Temp\RobotTempDir7524321172725900916\TestRunnerAgent.py:54402 --argumentfile C:\Users\DIPAK~1.BAC\AppData\Local\Temp\RobotTempDir7524321172725900916\args_ec8bf3c0.arg C:\Users\dipak.bachhav\imagecompare\Test
Suite Executor: Robot Framework 3.0.2 (Python 2.7.11 on win32)
==============================================================================
Test                                                                          
==============================================================================
Test.Src                                                                      
==============================================================================
Test.Src.Image-Comparison                                                     
==============================================================================
Image Comparison Ok                                                   | FAIL |
Evaluating expression 'Version: ImageMagick 7.0.7-8 Q16 x64 2017-10-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo flif freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps raw rsvg tiff webp xml zlib
Usage: compare [options ...] image reconstruct difference

Image Settings:
  -alpha option        on, activate, off, deactivate, set, opaque, copy
                       transparent, extract, background, or shape
  -authenticate password
                       decipher image with this password
  -background color    background color
  -colorspace type     alternate image colorspace
  -compose operator    set image composite operator
  -compress type       type of pixel compression when writing the image
  -decipher filename   convert cipher pixels to plain pixels
    [ Message content over the limit has been removed. ]

Image Sequence Operators:
  -crop geometry       cut out a rectangular region of the image

Image Stack Operators:
  -delete indexes      delete the image from the image sequence

Miscellaneous Options:
  -channel mask        set the image channel mask
  -debug events        display copious debugging information
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information

By default, the image format of 'file' is determined by its magic
number.  To specify a particular image format, precede the filename
with an image format name and a colon (i.e. ps:image) or specify the
image type as the filename suffix (i.e. image.ps).  Specify 'file' as
'-' for standard input or output. < C:\Users\dipak.bachhav\imagecompare\reference101.png' failed: SyntaxError: invalid syntax (<string>, line 1)
------------------------------------------------------------------------------
Test.Src.Image-Comparison                                             | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Test.Src                                                              | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Test                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\dipak.bachhav\imagecompare\Test\output.xml
Log:     C:\Users\dipak.bachhav\imagecompare\Test\log.html
Report:  C:\Users\dipak.bachhav\imagecompare\Test\report.html

**Comment by dipakbachhav** [comment]
KEYWORD ${TEMP} = String . Replace String ${IMAGE_COMPARATOR_COMMAND}, __REFERENCE__, ${Reference_Image_Path}
Documentation:	
Replaces search_for in the given string with replace_with.
Start / End / Elapsed:	20171017 15:08:26.097 / 20171017 15:08:26.098 / 00:00:00.001
15:08:26.098	INFO	${TEMP} = C:\"Program Files"\ImageMagick-7.0.7-Q16\compare.exe	
00:00:00.001KEYWORD BuiltIn . Log ${TEMP}
00:00:00.001KEYWORD ${COMMAND} = String . Replace String ${TEMP}, __TEST__, ${Test_Image_Path}
Documentation:	
Replaces search_for in the given string with replace_with.
Start / End / Elapsed:	20171017 15:08:26.100 / 20171017 15:08:26.101 / 00:00:00.001
15:08:26.101	INFO	${COMMAND} = C:\"Program Files"\ImageMagick-7.0.7-Q16\compare.exe	
00:00:00.001KEYWORD BuiltIn . Log ${COMMAND}
Documentation:	
Logs the given message with the given level.
Start / End / Elapsed:	20171017 15:08:26.102 / 20171017 15:08:26.103 / 00:00:00.001
15:08:26.102	INFO	C:\"Program Files"\ImageMagick-7.0.7-Q16\compare.exe	
00:00:00.003KEYWORD BuiltIn . Log Executing: ${COMMAND}
Documentation:	
Logs the given message with the given level.
Start / End / Elapsed:	20171017 15:08:26.103 / 20171017 15:08:26.106 / 00:00:00.003
15:08:26.104	INFO	Executing: C:\"Program Files"\ImageMagick-7.0.7-Q16\compare.exe	
00:00:00.038KEYWORD ${RC}, ${OUTPUT} = OperatingSystem . Run And Return Rc And Output ${COMMAND}
Documentation:	
Runs the given command in the system and returns the RC and output.
Start / End / Elapsed:	20171017 15:08:26.106 / 20171017 15:08:26.144 / 00:00:00.038
15:08:26.111	INFO	Running command 'C:\"Program Files"\ImageMagick-7.0.7-Q16\compare.exe 2>&1'.	
15:08:26.143	INFO	${RC} = 2	
15:08:26.144	INFO	${OUTPUT} = Version: ImageMagick 7.0.7-8 Q16 x64 2017-10-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: ...	
00:00:00.001KEYWORD BuiltIn . Log Return Code: ${RC}
00:00:00.001KEYWORD BuiltIn . Log Return Output: ${OUTPUT}
