### ISSUE TITLE
How to compare images with robot framework in window based environement ? 

### ISSUE THREAD

**Issue by dipakbachhav** [ThomasJaspers/robot-framework-image-comparison#2]
@ThomasJaspers : Mistakenly I closed old issue so creating newone . I am using imagemagick to compare two screenshots in windows . Is it possible for you to provide example in window based system.https://blog.codecentric.de/en/2017/09/robot-framework-compare-images-screenshots/

```

*** Settings ***
Library   String
Library   OperatingSystem

*** Variables ***
${IMAGE_COMPARATOR_COMMAND}   C:\\"Program Files"\\ImageMagick-7.0.7-Q16\\convert.exe


*** Test Cases ***
Image Comparison Ok
  Compare Images    C:/Users/user/imagecompare/Test/src/reference-screenshots/reference-1.png    C:/Users/user/imagecompare/Test/src/test-screenshots/test-1.png   0.1


Image Comparison NOk
  Compare Images    C:/Users/user/imagecompare/Test/src/reference-screenshots/reference-1.png    C:/Users/user/imagecompare/Test/src/test-screenshots/test-1.png   0.1

*** Keywords ***
Compare Images
   [Arguments]      ${Reference_Image_Path}    ${Test_Image_Path}    ${Allowed_Threshold}
   ${TEMP}=         Replace String     ${IMAGE_COMPARATOR_COMMAND}    __REFERENCE__     ${Reference_Image_Path}
   ${COMMAND}=      Replace String     ${TEMP}    __TEST__     ${Test_Image_Path}
   Log              Executing: ${COMMAND}
   ${RC}            ${OUTPUT}=     Run And Return Rc And Output     ${COMMAND}
   Log              Return Code: ${RC}
   Log              Return Output: ${OUTPUT}
   ${RESULT}        Evaluate    ${OUTPUT} < ${Allowed_Threshold}
   Should be True   ${RESULT}



```
But facing issue with above code. :: 

```
Kindly find below issue . i have tried to compare same image but failed. Also I am using windows environment. Please help me out as i am seriously struggling with image comparison from past 2 weeks.

Evaluates the given expression in Python and returns the results.
Start / End / Elapsed:	20171017 15:02:12.842 / 20171017 15:02:12.843 / 00:00:00.001
15:02:12.843	FAIL	Evaluating expression 'Version: ImageMagick 7.0.7-8 Q16 x64 2017-10-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps raw rsvg tiff webp xml zlib
Usage: compare.exe [options ...] image reconstruct difference

Image Settings:
-alpha option on, activate, off, deactivate, set, opaque, copy
transparent, extract, background, or shape
-authenticate password
decipher image with this password
-background color background color
-colorspace type alternate image colorspace
-compose operator set image composite operator
-compress type type of pixel compression when writing the image
-decipher filename convert cipher pixels to plain pixels
-define format:option
define one or more image format options
-density geometry horizontal and vertical density of the image
-depth value image depth
-dissimilarity-threshold value
maximum distortion for (sub)image match
-encipher filename convert plain pixels to cipher pixels
-extract geometry extract area from image
-format "string" output formatted image characteristics
-fuzz distance colors within this distance are considered equal
-gravity type horizontal and vertical text placement
-highlight-color color
empasize pixel differences with this color
-identify identify the format and characteristics of the image
-interlace type type of image interlacing scheme
-limit type value pixel cache resource limit
-lowlight-color color
de-emphasize pixel differences with this color
-metric type measure differences between images with this metric
-monitor monitor progress
-negate replace every pixel with its complementary color
-profile filename add, delete, or apply an image profile
-quality value JPEG/MIFF/PNG compression level
-quiet suppress all warning messages
-quantize colorspace reduce colors in this colorspace
-read-mask filename associate a read mask with the image
-regard-warnings pay attention to warning messages
-respect-parentheses settings remain in effect until parenthesis boundary
-sampling-factor geometry
horizontal and vertical sampling factor
-seed value seed a new sequence of pseudo-random numbers
-set attribute value set an image attribute
-quality value JPEG/MIFF/PNG compression level
-repage geometry size and location of an image canvas
-similarity-threshold value
minimum distortion for (sub)image match
-size geometry width and height of image
-subimage-search search for subimage
-synchronize synchronize image to storage device
-taint declare the image as modified
-transparent-color color
transparent color
-type type image type
-verbose print detailed information about the image
-version print version information
-virtual-pixel method
virtual pixel access method
-write-mask filename associate a write mask with the image

Image Operators:
-brightness-contrast geometry
improve brightness / contrast of the image
-distort method args
distort images according to given method and args
-level value adjust the level of image contrast
-resize geometry resize the image
-rotate degrees apply Paeth rotation to the image
-sigmoidal-contrast geometry
increase the contrast without saturating highlights or
-trim trim image edges
-write filename write images to this file

Image Channel Operators:
-separate separate an image channel into a grayscale image

Image Sequence Operators:
-crop geometry cut out a rectangular region of the image

Image Stack Operators:
-delete indexes delete the image from the image sequence

Miscellaneous Options:
-channel mask set the image channel mask
-debug events display copious debugging information
-help print program options
-list type print a list of supported option arguments
-log format format of debugging information

By default, the image format of 'file' is determined by its magic
number. To specify a particular image format, precede the filename
with an image format name and a colon (i.e. ps:image) or specify the
image type as the filename suffix (i.e. image.ps). Specify 'file' as
'-' for standard input or output. < 0.1' failed: SyntaxError: invalid syntax (, line 1)
```

```
KEYWORD ${TEMP} = String . Replace String ${IMAGE_COMPARATOR_COMMAND}, REFERENCE, ${Reference_Image_Path}
Documentation:
Replaces search_for in the given string with replace_with.
Start / End / Elapsed:	20171017 15:08:26.097 / 20171017 15:08:26.098 / 00:00:00.001
15:08:26.098	INFO	${TEMP} = C:"Program Files"\ImageMagick-7.0.7-Q16\compare.exe
00:00:00.001KEYWORD BuiltIn . Log ${TEMP}
00:00:00.001KEYWORD ${COMMAND} = String . Replace String ${TEMP}, TEST, ${Test_Image_Path}
Documentation:
Replaces search_for in the given string with replace_with.
Start / End / Elapsed:	20171017 15:08:26.100 / 20171017 15:08:26.101 / 00:00:00.001
15:08:26.101	INFO	${COMMAND} = C:"Program Files"\ImageMagick-7.0.7-Q16\compare.exe
00:00:00.001KEYWORD BuiltIn . Log ${COMMAND}
Documentation:
Logs the given message with the given level.
Start / End / Elapsed:	20171017 15:08:26.102 / 20171017 15:08:26.103 / 00:00:00.001
15:08:26.102	INFO	C:"Program Files"\ImageMagick-7.0.7-Q16\compare.exe
00:00:00.003KEYWORD BuiltIn . Log Executing: ${COMMAND}
Documentation:
Logs the given message with the given level.
Start / End / Elapsed:	20171017 15:08:26.103 / 20171017 15:08:26.106 / 00:00:00.003
15:08:26.104	INFO	Executing: C:"Program Files"\ImageMagick-7.0.7-Q16\compare.exe
00:00:00.038KEYWORD ${RC}, ${OUTPUT} = OperatingSystem . Run And Return Rc And Output ${COMMAND}
Documentation:
Runs the given command in the system and returns the RC and output.
Start / End / Elapsed:	20171017 15:08:26.106 / 20171017 15:08:26.144 / 00:00:00.038
15:08:26.111	INFO	Running command 'C:"Program Files"\ImageMagick-7.0.7-Q16\compare.exe 2>&1'.
15:08:26.143	INFO	${RC} = 2
15:08:26.144	INFO	${OUTPUT} = Version: ImageMagick 7.0.7-8 Q16 x64 2017-10-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: ...
00:00:00.001KEYWORD BuiltIn . Log Return Code: ${RC}
00:00:00.001KEYWORD BuiltIn . Log Return Output: ${OUTPUT}
```

**Comment by ThomasJaspers** [comment]
I think the problem is in your definition of the IMAGE_COMPARATOR_COMMAND.
This look originally as follows

${IMAGE_COMPARATOR_COMMAND}   /usr/local/Cellar/imagemagick/7.0.7-3/bin/convert __REFERENCE__ __TEST__ -metric RMSE -compare -format  "%[distortion]" info:

It is replacing then the values for __REFERENCE__ and __TEST__ with the given image paths given as parameter. As this does not happen in your case you simply only see the help message of the compare-command.

Hope this helps :-).

**Comment by dipakbachhav** [comment]
Hi @ThomasJaspers ,

Actually i am using windows environment to compare images . Below is the path where i have installed ImageMagick. C:\Program Files\ImageMagick-7.0.7-Q16.

I am struggling with image comparison from past two weeks. But did not find any solution yet. Could you please help me to solve my issue because i am new to robot framework & struggling so badly. 

If you have any small example which help me to solve my issue then please provide me that.

Environment : 
 Windows 7 (64 bit)
ImageMagick-7.0.7-Q16.

**Comment by ThomasJaspers** [comment]
Please try the following:

<pre>
*** Settings ***
Library   String
Library   OperatingSystem

*** Variables ***
${IMAGE_COMPARATOR_COMMAND}     C:\\"Program Files"\\ImageMagick-7.0.7-Q16\\convert.exe __REFERENCE__ __TEST__ -metric RMSE -compare -format "%[distortion]" info:

*** Test Cases ***
Image Comparison Ok
  Compare Images    C:/Users/user/imagecompare/Test/src/reference-screenshots/reference-1.png    C:/Users/user/imagecompare/Test/src/test-screenshots/test-1.png   0.1

Image Comparison NOk
  Compare Images    C:/Users/user/imagecompare/Test/src/reference-screenshots/reference-1.png    C:/Users/user/imagecompare/Test/src/test-screenshots/test-1.png   0.1

*** Keywords ***
Compare Images
   [Arguments]      ${Reference_Image_Path}    ${Test_Image_Path}    ${Allowed_Threshold}
   ${TEMP}=         Replace String     ${IMAGE_COMPARATOR_COMMAND}    __REFERENCE__     ${Reference_Image_Path}
   ${COMMAND}=      Replace String     ${TEMP}    __TEST__     ${Test_Image_Path}
   Log              Executing: ${COMMAND}
   ${RC}            ${OUTPUT}=     Run And Return Rc And Output     ${COMMAND}
   Log              Return Code: ${RC}
   Log              Return Output: ${OUTPUT}
   ${RESULT}        Evaluate    ${OUTPUT} < ${Allowed_Threshold}
   Should be True   ${RESULT}
</pre>

**Comment by dipakbachhav** [comment]
Wow..it's working ... you are simply awesome ...Thank yo so much ...

**Comment by ThomasJaspers** [comment]
Glad to hear it is working ... your're welcome :-)

**Comment by dipakbachhav** [comment]
Hi @ThomasJaspers : Actually sorry to disturb you one more time but when i integrated above code in my framework in that case after below code remaining code is not executed . Can you please check and let me  know your valuable thoughts. 
`*** Settings ***
Library         String
Library         OperatingSystem

*** Variables ***
${IMAGE_COMPARATOR_COMMAND}     C:\\"Program Files"\\ImageMagick-7.0.7-Q16\\convert.exe __REFERENCE__ __TEST__ -metric RMSE -compare -format "%[distortion]" info:


*** Test Cases ***	
Image Comparison NotOk
  Compare Images       C:/Users/dipak.bachhav/imagecompare/Test/src/test-screenshots/test-2.png     C:/Users/dipak.bachhav/imagecompare/Test/src/test-screenshots/test-2.png   0.1
	
*** Keywords ***
Compare Images
   [Arguments]      ${Reference_Image_Path}    ${Test_Image_Path}    ${Allowed_Threshold}
   ${TEMP}=         Replace String     ${IMAGE_COMPARATOR_COMMAND}    __REFERENCE__     ${Reference_Image_Path}
   ${COMMAND}=      Replace String     ${TEMP}    __TEST__     ${Test_Image_Path}
   Log              Executing: ${COMMAND}` 

 Problem is with below statment
` ${RC}            ${OUTPUT}=     Run And Return Rc And Output     ${COMMAND}`

Log
`TEST Image Comparison NotOk
Full Name:	Acceptance.Image Comparison NotOk
Start / End / Elapsed:	20171021 11:23:15.531 / 20171021 11:23:15.668 / 00:00:00.137
Status:	PASS (critical)
00:00:00.101KEYWORD Compare Images C:/Users/username/imagecompare/Test/src/test-screenshots/test-2.png, C:/Users/username/imagecompare/Test/src/test-screenshots/test-2.png, 0.1
Start / End / Elapsed:	20171021 11:23:15.549 / 20171021 11:23:15.650 / 00:00:00.101
00:00:00.018KEYWORD ${TEMP} = String . Replace String ${IMAGE_COMPARATOR_COMMAND}, __REFERENCE__, ${Reference_Image_Path}
Documentation:	
Replaces search_for in the given string with replace_with.
Start / End / Elapsed:	20171021 11:23:15.576 / 20171021 11:23:15.594 / 00:00:00.018
11:23:15.592	INFO	${TEMP} = C:\"Program Files"\ImageMagick-7.0.7-Q16\convert.exe C:/Users/username/imagecompare/Test/src/test-screenshots/test-2.png __TEST__ -metric RMSE -compare -format "%[distortion]" info:	
00:00:00.011KEYWORD ${COMMAND} = String . Replace String ${TEMP}, __TEST__, ${Test_Image_Path}
Documentation:	
Replaces search_for in the given string with replace_with.
Start / End / Elapsed:	20171021 11:23:15.608 / 20171021 11:23:15.619 / 00:00:00.011
11:23:15.618	INFO	${COMMAND} = C:\"Program Files"\ImageMagick-7.0.7-Q16\convert.exe C:/Users/username/imagecompare/Test/src/test-screenshots/test-2.png C:/Users/username/imagecompare/Test/src/test-screenshots/test-2.png -...	
00:00:00.019KEYWORD BuiltIn . Log Executing: ${COMMAND}
Documentation:	
Logs the given message with the given level.
Start / End / Elapsed:	20171021 11:23:15.625 / 20171021 11:23:15.644 / 00:00:00.019
11:23:15.638	INFO	Executing: C:\"Program Files"\ImageMagick-7.0.7-Q16\convert.exe C:/Users/username/imagecompare/Test/src/test-screenshots/test-2.png C:/Users/username/imagecompare/Test/src/test-screenshots/test-2.png -metric RMSE -compare -format "%[distortion]" info:`
